//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChicoDoColchao.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaFiscal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotaFiscal()
        {
            this.NotaFiscalProduto = new HashSet<NotaFiscalProduto>();
        }
    
        public int NotaFiscalID { get; set; }
        public int Numero { get; set; }
        public System.DateTime DataNotaFiscal { get; set; }
        public int LojaID { get; set; }
        public Nullable<int> PedidoMaeID { get; set; }
        public bool Ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaFiscalProduto> NotaFiscalProduto { get; set; }
        public virtual Loja Loja { get; set; }
    }
}
