//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChicoDoColchao.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrcamentoHistorico
    {
        public int OrcamentoHistoricoID { get; set; }
        public int OrcamentoID { get; set; }
        public string Observacao { get; set; }
        public System.DateTime DataCadastro { get; set; }
    
        public virtual Orcamento Orcamento { get; set; }
    }
}
