//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChicoDoColchao.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orcamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orcamento()
        {
            this.OrcamentoProduto = new HashSet<OrcamentoProduto>();
            this.OrcamentoHistorico = new HashSet<OrcamentoHistorico>();
        }
    
        public int OrcamentoID { get; set; }
        public int LojaID { get; set; }
        public int FuncionarioID { get; set; }
        public System.DateTime DataOrcamento { get; set; }
        public string Observacao { get; set; }
        public bool Ativo { get; set; }
        public int ClienteID { get; set; }
        public double Desconto { get; set; }
        public Nullable<int> PedidoID { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrcamentoProduto> OrcamentoProduto { get; set; }
        public virtual Orcamento Orcamento1 { get; set; }
        public virtual Orcamento Orcamento2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrcamentoHistorico> OrcamentoHistorico { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Pedido Pedido { get; set; }
        public virtual Loja Loja { get; set; }
    }
}
