//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChicoDoColchao.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoTipoPagamento
    {
        public int PedidoTipoPagamentoID { get; set; }
        public int PedidoID { get; set; }
        public int TipoPagamentoID { get; set; }
        public int ParcelaID { get; set; }
        public double ValorPago { get; set; }
    
        public virtual Parcela Parcela { get; set; }
        public virtual Pedido Pedido { get; set; }
        public virtual TipoPagamento TipoPagamento { get; set; }
    }
}
