//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChicoDoColchao.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.PedidoProduto = new HashSet<PedidoProduto>();
            this.PedidoTipoPagamento = new HashSet<PedidoTipoPagamento>();
        }
    
        public int PedidoID { get; set; }
        public int Numero { get; set; }
        public int FuncionarioID { get; set; }
        public int ClienteID { get; set; }
        public System.DateTime DataPedido { get; set; }
        public Nullable<System.DateTime> DataEntrega { get; set; }
        public int LojaOrigemID { get; set; }
        public int LojaSaidaID { get; set; }
        public int PedidoStatusID { get; set; }
        public string Observacao { get; set; }
        public string NomeCarreto { get; set; }
        public Nullable<double> ValorFrete { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual Loja Loja { get; set; }
        public virtual Loja Loja1 { get; set; }
        public virtual PedidoStatus PedidoStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoProduto> PedidoProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoTipoPagamento> PedidoTipoPagamento { get; set; }
    }
}
