//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChicoDoColchao.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transferencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transferencia()
        {
            this.TransferenciaProduto = new HashSet<TransferenciaProduto>();
        }
    
        public int TransferenciaID { get; set; }
        public int LojaOrigemID { get; set; }
        public int LojaDestinoID { get; set; }
        public System.DateTime DataTransferencia { get; set; }
        public string Observacao { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Loja Loja { get; set; }
        public virtual Loja Loja1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferenciaProduto> TransferenciaProduto { get; set; }
    }
}
